<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
    <fieldUpdates>
        <fullName>ApprovalAction</fullName>
        <field>Type</field>
        <literalValue>Customer</literalValue>
        <name>ApprovalAction</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>RejectStep</fullName>
        <field>Type</field>
        <literalValue>Prospect</literalValue>
        <name>RejectStep</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Typeupdate</fullName>
        <field>Type</field>
        <literalValue>Pending</literalValue>
        <name>Typeupdate</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <outboundMessages>
        <fullName>AccountOutboundMessage</fullName>
        <apiVersion>38.0</apiVersion>
        <endpointUrl>https://clarcor-sfdc-soa.clarcor.net:8001/integration/flowsvc/salesforce/default/CLCSFDCAccountOutboundListener/SFDCOutboundAccountAdapter/v1.0/?wsdl</endpointUrl>
        <fields>AccountNumber</fields>
        <fields>AccountSource</fields>
        <fields>Active__c</fields>
        <fields>AnnualRevenue</fields>
        <fields>BillingCity</fields>
        <fields>BillingCountry</fields>
        <fields>BillingGeocodeAccuracy</fields>
        <fields>BillingLatitude</fields>
        <fields>BillingLongitude</fields>
        <fields>BillingPostalCode</fields>
        <fields>BillingState</fields>
        <fields>BillingStreet</fields>
        <fields>CleanStatus</fields>
        <fields>CreatedById</fields>
        <fields>CreatedDate</fields>
        <fields>CustomerPriority__c</fields>
        <fields>DandbCompanyId</fields>
        <fields>Description</fields>
        <fields>Distance__c</fields>
        <fields>DunsNumber</fields>
        <fields>Fax</fields>
        <fields>Id</fields>
        <fields>Industry</fields>
        <fields>IsDeleted</fields>
        <fields>IsExcludedFromRealign</fields>
        <fields>Jigsaw</fields>
        <fields>JigsawCompanyId</fields>
        <fields>LastActivityDate</fields>
        <fields>LastModifiedById</fields>
        <fields>LastModifiedDate</fields>
        <fields>LastReferencedDate</fields>
        <fields>LastViewedDate</fields>
        <fields>MasterRecordId</fields>
        <fields>Match_Billing_Address__c</fields>
        <fields>NaicsCode</fields>
        <fields>NaicsDesc</fields>
        <fields>Name</fields>
        <fields>NumberOfEmployees</fields>
        <fields>NumberofLocations__c</fields>
        <fields>OwnerId</fields>
        <fields>Ownership</fields>
        <fields>ParentId</fields>
        <fields>Phone</fields>
        <fields>PhotoUrl</fields>
        <fields>Rating</fields>
        <fields>SLAExpirationDate__c</fields>
        <fields>SLASerialNumber__c</fields>
        <fields>SLA__c</fields>
        <fields>ShippingCity</fields>
        <fields>ShippingCountry</fields>
        <fields>ShippingGeocodeAccuracy</fields>
        <fields>ShippingLatitude</fields>
        <fields>ShippingLongitude</fields>
        <fields>ShippingPostalCode</fields>
        <fields>ShippingState</fields>
        <fields>ShippingStreet</fields>
        <fields>Sic</fields>
        <fields>SicDesc</fields>
        <fields>Site</fields>
        <fields>SystemModstamp</fields>
        <fields>TickerSymbol</fields>
        <fields>Tradestyle</fields>
        <fields>Type</fields>
        <fields>UpsellOpportunity__c</fields>
        <fields>Website</fields>
        <fields>YearStarted</fields>
        <includeSessionId>false</includeSessionId>
        <integrationUser>sarath.sfp@gmail.com</integrationUser>
        <name>AccountOutboundMessage</name>
        <protected>false</protected>
        <useDeadLetterQueue>false</useDeadLetterQueue>
    </outboundMessages>
    <outboundMessages>
        <fullName>AccountOutboundMessage1</fullName>
        <apiVersion>38.0</apiVersion>
        <endpointUrl>https://clarcor-sfdc-soa.clarcor.net:8001/integration/flowsvc/salesforce/default/CLCSFDCAccountOutboundListener/SFDCOutboundAccountAdapter/v1.0/?wsdl</endpointUrl>
        <fields>AccountNumber</fields>
        <fields>AccountSource</fields>
        <fields>Active__c</fields>
        <fields>AnnualRevenue</fields>
        <fields>BillingCity</fields>
        <fields>BillingCountry</fields>
        <fields>BillingGeocodeAccuracy</fields>
        <fields>BillingLatitude</fields>
        <fields>BillingLongitude</fields>
        <fields>BillingPostalCode</fields>
        <fields>BillingState</fields>
        <fields>BillingStreet</fields>
        <fields>CleanStatus</fields>
        <fields>CreatedById</fields>
        <fields>CreatedDate</fields>
        <fields>CustomerPriority__c</fields>
        <fields>DandbCompanyId</fields>
        <fields>Id</fields>
        <includeSessionId>false</includeSessionId>
        <integrationUser>sarath.sfp@gmail.com</integrationUser>
        <name>AccountOutboundMessage1</name>
        <protected>false</protected>
        <useDeadLetterQueue>false</useDeadLetterQueue>
    </outboundMessages>
    <rules>
        <fullName>Account_OutboundMsgTest</fullName>
        <actions>
            <name>AccountOutboundMessage</name>
            <type>OutboundMessage</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Account.Name</field>
            <operation>notEqual</operation>
            <value>Null</value>
        </criteriaItems>
        <triggerType>onAllChanges</triggerType>
    </rules>
</Workflow>
