public class StudentRegistration {
    public String name {set;get;}
    public Integer age {set;get;}
    public String address {set;get;}
    public Integer rollNumber {set;get;}
    Public Boolean flag {set;get;}
    public String password {set;get;}
    public void submit() {
      }
    public void cancel (){
   
        name = null;
        age = null;
        address = null;
        rollNumber = null;
        flag = null;
        password = null;
        
    }
    

}